### ISSUE TITLE
Issues with Location column type

### ISSUE THREAD

**Issue by brentleejcass** [trix-solutions/moncli#239]
I've recently started working with location column type in my boards. When trying to just get_items() from the board, I have been seeing the below error. The first time I received it, I assumed it was an issue with my column, so I deleted the column, replaced it with a new location column, then the problem was gone. I ran my script for about a week with the new column and then started seeing this error again today, so of course I have too much data now to just delete and replace again. I'm assuming that one of the locations selected on an item is missing a Lat value, but I don't have any way to see that in the UI, because the location values are just selected from the dropdown, and of course I can't pull the list of items, because I get this error. Any ideas how to avoid this error or a fix that can account for it? 

`Traceback (most recent call last):
  File "/Users/brentleecass/PycharmProjects/monday_practice/upcoming_expansions_automations.py", line 77, in <module>
    scheduled_items = scheduled_items_group.get_items('name')  # pull items in scheduled items group
  File "/Users/brentleecass/PycharmProjects/monday_practice/venv/lib/python3.9/site-packages/moncli/entities/group.py", line 359, in get_items
    items = [en.Item(creds=self.__creds, **item_data) for item_data in items_data] 
  File "/Users/brentleecass/PycharmProjects/monday_practice/venv/lib/python3.9/site-packages/moncli/entities/group.py", line 359, in <listcomp>
    items = [en.Item(creds=self.__creds, **item_data) for item_data in items_data] 
  File "/Users/brentleecass/PycharmProjects/monday_practice/venv/lib/python3.9/site-packages/moncli/entities/item.py", line 147, in __init__
    self.__column_values.append(cv.create_column_value(column.column_type, settings_str=column.settings_str, **data))
  File "/Users/brentleecass/PycharmProjects/monday_practice/venv/lib/python3.9/site-packages/moncli/column_value/__init__.py", line 22, in create_column_value
    return getattr(
  File "/Users/brentleecass/PycharmProjects/monday_practice/venv/lib/python3.9/site-packages/moncli/column_value/base.py", line 57, in __init__
    self._value = self._convert(value)
  File "/Users/brentleecass/PycharmProjects/monday_practice/venv/lib/python3.9/site-packages/moncli/column_value/simple.py", line 216, in _convert
    return Location(lat=value['lat'],lng=value['lng'],address=value['address'])
KeyError: 'lat'`

**Comment by RDFormations** [comment]
hey i have the same problem, did you found any solution ?

**Comment by brentleejcass** [comment]
Unfortunately no. Since I just needed to view the location name on the board that I was moving this info to I ended up just converting the location to text and putting that into the board rather than the actual location value. Not a great solution, but I couldn't find a fix otherwise.
