### ISSUE TITLE
DataError when finding file_column to upload item in v1.0

### ISSUE THREAD

**Issue by Knowaaaa** [trix-solutions/moncli#85]
This is the column that I am attempting to access to upload the file to:  

{'id': 'files1', 'title': 'Completion Files', 'text':''}

Here is the portion of my script that gets the correct item that I want to upload files to, and the correct column. 

```
items = board.get_items(ids=[self.customer.idnum])
item = items[0]
filecol = item.get_column_value(id='files1')  
item.add_file(filepath,file_column=filecol)
```

Once the script reaches this point, it gives a DataError:  

```
Traceback (most recent call last):
  File "c:\Python38\Scripts\Projects\BarkerConstructionLLC\Monday_Client.py", line 169, in <module>    
    find_and_fill(root)
  File "c:\Python38\Scripts\Projects\BarkerConstructionLLC\Monday_Client.py", line 86, in find_and_fill
    doc.fill(customer)
  File "c:\Python38\Scripts\Projects\BarkerConstructionLLC\docs.py", line 130, in fill
    filecol = item.get_column_value(id='files1')
  File "C:\Python\lib\site-packages\moncli\entities\item.py", line 577, in get_column_value
    for column_value in self.get_column_values(*args):
  File "C:\Python\lib\site-packages\moncli\entities\item.py", line 528, in get_column_values
    if columns_map[id].settings:
  File "C:\Python\lib\site-packages\moncli\entities\objects.py", line 124, in settings
    return StatusSettings(settings_obj)
  File "C:\Python\lib\site-packages\schematics\models.py", line 232, in __init__
    data = self._convert(raw_data,
  File "C:\Python\lib\site-packages\schematics\models.py", line 299, in _convert
    return func(self._schema, self, raw_data=raw_data, oo=True, context=context, **kwargs)
  File "C:\Python\lib\site-packages\schematics\transforms.py", line 428, in convert
    return import_loop(cls, mutable, raw_data, import_converter, **kwargs)
  File "C:\Python\lib\site-packages\schematics\transforms.py", line 174, in import_loop
    raise DataError(errors, data)
schematics.exceptions.DataError: {"done_colors": "Rogue field", "hide_footer": "Rogue field"}
```  
  
I am not sure if the issue is on my end, but I am also confused on whether I should be using this method https://github.com/trix-solutions/moncli#item or this https://github.com/trix-solutions/moncli#uploading-files method to upload files. 

Thanks a lot guys!

**Comment by Ashatz** [comment]
Hello @Knowaaaa,

This was an issue on our side.  Those settings_str property that comes from monday.com as part of the board columns is quite fickle, and these fields were not added into the appropriate data model.  They have been added. 

Also, I have updated the documentation to reflect the correct way to upload files (based on the second link you provided, the first one was incorrect).  The fix has been uploaded and is ready to install.  Please let me know if this works for you!

**Comment by Knowaaaa** [comment]
```
  filecol = item.get_column_value(id='files1')
  File "C:\Python\lib\site-packages\moncli\entities\item.py", line 577, in get_column_value
    for column_value in self.get_column_values(*args):
  File "C:\Python\lib\site-packages\moncli\entities\item.py", line 528, in get_column_values
    if columns_map[id].settings:
  File "C:\Python\lib\site-packages\moncli\entities\objects.py", line 126, in settings
    return DropdownSettings(settings_obj)
  File "C:\Python\lib\site-packages\schematics\models.py", line 232, in __init__
    data = self._convert(raw_data,
  File "C:\Python\lib\site-packages\schematics\models.py", line 299, in _convert
    return func(self._schema, self, raw_data=raw_data, oo=True, context=context, **kwargs)
  File "C:\Python\lib\site-packages\schematics\transforms.py", line 428, in convert
    return import_loop(cls, mutable, raw_data, import_converter, **kwargs)
  File "C:\Python\lib\site-packages\schematics\transforms.py", line 174, in import_loop
    raise DataError(errors, data)
schematics.exceptions.DataError: {"hide_footer": "Rogue field"}
```

I now receive a different Rogue field error.

**Comment by Ashatz** [comment]
@Knowaaaa,

This looks to be a the same error on a different object.  I have patched a fix. Please let me know if this works.

Thanks!

**Comment by Ashatz** [comment]
@Knowaaaa, I have not heard back from you regarding this change.  I am closing out this issue.  Please feel free to open another issue should you run into anything.
