### ISSUE TITLE
Doesnt work with "color mapping"

### ISSUE THREAD

**Issue by marcuslow** [trix-solutions/moncli#86]
Getting column value where the rows have colors bombs out with an exception.

```
ERROR] DataError: 
{
    "color_mapping": "Rogue field"
}
```

My code iterate thru each row getting the value of a column as item.

```
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 293, in lambda_handler
    Start()
  File "/var/task/lambda_function.py", line 274, in Start
    colvalue = x.get_column_value(id=g_IdsColumnToSearch)
  File "/opt/python/lib/python3.7/site-packages/moncli/entities/item.py", line 577, in get_column_value
    for column_value in self.get_column_values(*args):
  File "/opt/python/lib/python3.7/site-packages/moncli/entities/item.py", line 528, in get_column_values
    if columns_map[id].settings:
  File "/opt/python/lib/python3.7/site-packages/moncli/entities/objects.py", line 124, in settings
    return StatusSettings(settings_obj)
  File "/opt/python/lib/python3.7/site-packages/schematics/models.py", line 235, in __init__
    app_data=app_data, **kwargs)
  File "/opt/python/lib/python3.7/site-packages/schematics/models.py", line 299, in _convert
    return func(self._schema, self, raw_data=raw_data, oo=True, context=context, **kwargs)
  File "/opt/python/lib/python3.7/site-packages/schematics/transforms.py", line 428, in convert
    return import_loop(cls, mutable, raw_data, import_converter, **kwargs)
  File "/opt/python/lib/python3.7/site-packages/schematics/transforms.py", line 174, in import_loop
    raise DataError(errors, data)
```

**Comment by booey811** [comment]
Hi All,

I'm receiving exactly the same error also. Happy to share more information if required but for now I thought I would just confirm the exception.

**Comment by Ashatz** [comment]
@marcuslow, @booey811.  I have added in a change that I believe should fix your issues.  If this works, please feel free to close out this issue. Thank you for your feedback!

**Comment by booey811** [comment]
Hi @Ashatz,

Thanks for the quick response! I shall test this afternoon :)

**Comment by Ashatz** [comment]
I have not heard back as far as fixes are concerned and am closing out this issue.  Please feel free to submit another issue if you run across one.  

Happy coding!

**Comment by marcuslow** [comment]
@Ashatz  yes it works, i ran it for a week and no issues.
